services:
 bot-app:
    build: .
    depends_on:
      bot-db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
 bot-db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - bot-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
 bot-postgres-data: